### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Michionlion** [Michionlion/rayterm-poster#1]
* [x] Remove copyright notices from poster (preserve in `README.md`)
* [x] Update center image to include reflective material version
* [x] Figure out QR-code vs QR code etc.
* [x] Figure out sizes
* [x] Debate youtube video link
